core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ItemDetailView, CheckoutView, HomeView, add_to_cart, add_single_item, remove_from_cart, OrderSummaryView, remove_single_item, PaymentView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('checkout', CheckoutView.as_view(), name="checkout"),
    path('order-summary', OrderSummaryView.as_view(), name="order-summary"),
    path('product/<slug>/', ItemDetailView.as_view(), name="product"),
    path('add-to-cart/<slug>', add_to_cart, name="add_to_cart"),
    path('remove-from-cart/<slug>', remove_from_cart, name="remove_from_cart"),
    path('remove-single-item/<slug>', remove_single_item,
         name="remove-single-item"),
    path('add-single-item/<slug>', add_single_item, name="add-single-item"),
    path('payments/', PaymentView.as_view(), name="payment")
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Item(models.Model):
    img = models.ImageField(upload_to='pics')
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    desc = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            'slug': self.slug
        })


class Orderitem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(Orderitem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    address = models.ForeignKey(
        'Address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total = total + order_item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zipc = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=60)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

templates/base.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    {% block extra_head %}
    {% endblock extra_head %}
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light mdb-color darken-2 scrolling-navbar">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="#" target="_blank">
                <strong class="blue-text" style="font-family: sans-serif;"> SHOPPER</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" style="color:white;" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon" style="color:white;"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;" href="/">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;" href="/checkout"
                            target="_blank">Checkout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;" href="#" target="_blank">Products</a>
                    </li>
                </ul>

                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;" href="#">Hey ! {{user}}</a>
                    </li>
                    <li class="nav-item">
                        <a href="/order-summary" class="nav-link waves-effect">
                            <span class="badge red z-depth-1 mr-1" style="color:white;">
                                {{request.user | cart_item_count}} </span>
                            <i class="fas fa-shopping-cart" style="color:white;"></i>
                            <span class="clearfix d-none d-sm-inline-block" style="color:white;"> Cart </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" style="color:white;"
                            href="{% url 'account_signup' %}">Register</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="#" class="nav-link waves-effect" style="color:white;" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://twitter.com/batcypher" style="color:white;" class="nav-link waves-effect"
                            target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->
    {% block content  %}
    {% endblock content %}
    <!--/.Footer-->
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 mdb-color darken-2 fadeIn pt-5 pt-5">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="#" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="https://twitter.com/batcypher" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="https://instagram.com/batcypher" target="_blank">
                <i class="fab fa-instagram mr-3"></i>
            </a>

            <a href="https://github.com/farazkhanfk7" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2019 Copyright:
            <a href="https://github.com/farazkhanfk7" target="_blank"> Faraz Khan @batcypher </a>
        </div>
        <!--/.Copyright-->

    </footer>

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();

    </script>
    {% block extra_script %}
    {% endblock extra_script %}
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
      <div class="view"
        style="background-image: url('https://images.unsplash.com/photo-1470309864661-68328b2cd0a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            {% if messages %}
            <div class="container pt-5">
              {% for message in messages %}
              <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message | escape }}</p>
              {% endfor %}
            </div>
            {% endif %}
            <h1 class="mb-4 pt-2">
              <strong>SHOPPER</strong>
            </h1>
            <p>
              <strong></strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Aware of this change in fashion choices, Shopper brings you a line of smart shirts online for
                fashion-forward women, men, boys and girls.</strong>
            </p>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div class="view"
        style="background-image: url('https://images.unsplash.com/photo-1479064555552-3ef4979f8908?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Wear what suits best on you.</strong>
            </h1>

            <p>
              <strong></strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Aware of this change in fashion choices, Shopper brings you a line of smart shirts online for
                fashion-forward women, men, boys and girls.</strong>
            </p>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/Second slide-->

  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color darken-2 lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card image-->
            <div class="view overlay">
              <img src="{{item.img.url}}" class="card-img-top" alt="">
              <a href="{{item.get_absolute_url}}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{item.get_category_display}}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.title}}
                    <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                  </a>
                </strong>
              </h5>


              <h4 class="font-weight-bold blue-text">
                <strong>
                  {% if item.discount_price %}
                  {{item.discount_price}}$
                  {% else %}
                  {{item.price}}$
                  {% endif %}
                </strong>
              </h4>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        {% endfor %}
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>

        <li class="page-item active">
          <a class="page-link" href="#">1
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    <!--Pagination-->

  </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/item_list.html
{% extends "base.html" %}

{% block content %}
<h2>This is the list of items:</h2>

{% for item in items %}
{{ item }}
{% endfor %}
{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill"></span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{object.get_total}}</strong>
        </li>
    </ul>

</div>

templates/ordersummary.html
{% extends "base.html" %}


{% block content %}
<div style="margin-top:100px;" class="mb-5">
    <div class=" container card text-center mb-5 p-4 col-10">
        <h1>Order Summary</h1>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Item Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <td>{{order_item.item.title}}</td>
                        <td>
                            {% if order_item.item.discount_price %}
                            <del>${{order_item.item.price}}</del> ${{ order_item.item.discount_price}}
                            {% else %}
                            ${{order_item.item.price}}
                            {% endif %}
                        </td>
                        <td><a href="{% url 'core:remove-single-item' order_item.item.slug %}"><i
                                    class="fas fa-minus-square mr-2"></i></a></i>{{order_item.quantity}}<a
                                href="{% url 'core:add-single-item' order_item.item.slug %}"><i
                                    class="fas fa-plus-square ml-2"></i></a></td>
                        <td>
                            {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_price}} <div class="mb-1 p-2 badge badge-pill badge-info">
                                (Saving :
                                ${{order_item.get_amount_saved}})</div>
                            {% else %}
                            ${{order_item.get_total_item_price}}
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{order_item.item.get_remove_from_cart_url}}">
                                <i class="fas fa-trash-alt alert alert-danger"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.get_total %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td><strong class="card-title">Total Payable Amount :</strong></td>
                        <td>$ {{object.get_total}}</td>
                        <td><a class="btn btn-secondary" href="/checkout">Proceed to checkout</a></td>
                    </tr>
                    {% else %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td><strong class="card-title btn primary-btn">No Item</strong></td>
                        <td>$ {{object.get_total}}</td>
                        <td><a class="btn btn-secondary" href="/">Continue Shopping</a></td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/product.html
{% extends "base.html" %}
{% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    {% if messages %}
    <div class="container">
      {% for message in messages %}
      <p {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{message | escape }}</p>
      {% endfor %}
    </div>
    {% endif %}

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="{{object.img.url}}" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{object.get_category_display}}</span>
            </a>
          </div>
          <p class="lead font-weight-bold">{{object.title}}</p>

          <p class="lead">
            {% if object.discount_price %}
            <span class="mr-1">
              <del>${{object.price}}</del>
            </span>
            <span>${{object.discount_price}}</span>
            {% else %}
            <span>${{object.price}}</span>
            {% endif %}
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>{{object.description}}</p>

          <!-- <form class="d-flex justify-content-left">
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form> -->
          <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p">Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
          <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p">Remove from cart
          </a>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->
{% endblock content %}